//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ricky8955555.CoolQ.FeatureResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BlacklistManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlacklistManagerResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ricky8955555.CoolQ.FeatureResources.BlacklistManagerResources", typeof(BlacklistManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已将 {0} 加入黑名单 ❥(ゝω・✿ฺ) 的本地化字符串。
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将管理员或机器人加入到黑名单 ─=≡Σ(((つ•̀ω•́)つ 的本地化字符串。
        /// </summary>
        internal static string AdministratorOrRobotCannotBeListInBlacklist {
            get {
                return ResourceManager.GetString("AdministratorOrRobotCannotBeListInBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不存在黑名单内 (ц｀ω´ц*) 的本地化字符串。
        /// </summary>
        internal static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 已存在黑名单内 (ц｀ω´ц*) 的本地化字符串。
        /// </summary>
        internal static string Existed {
            get {
                return ResourceManager.GetString("Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已将 {0} 移出黑名单 ❥(ゝω・✿ฺ) 的本地化字符串。
        /// </summary>
        internal static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
    }
}
