//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ricky8955555.CoolQ.FeatureResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CovidStatusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CovidStatusResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ricky8955555.CoolQ.FeatureResources.CovidStatusResources", typeof(CovidStatusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 （较昨日：{0}） 的本地化字符串。
        /// </summary>
        internal static string CompareToYesterday {
            get {
                return ResourceManager.GetString("CompareToYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计确诊：{0} 的本地化字符串。
        /// </summary>
        internal static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据截至：{0} 的本地化字符串。
        /// </summary>
        internal static string DataUpdatingTime {
            get {
                return ResourceManager.GetString("DataUpdatingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计死亡：{0} 的本地化字符串。
        /// </summary>
        internal static string Dead {
            get {
                return ResourceManager.GetString("Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计治愈：{0} 的本地化字符串。
        /// </summary>
        internal static string Healed {
            get {
                return ResourceManager.GetString("Healed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息处理失败了 (；´д｀)ゞ 的本地化字符串。
        /// </summary>
        internal static string IncorrectInfo {
            get {
                return ResourceManager.GetString("IncorrectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求失败了 (；´д｀)ゞ 的本地化字符串。
        /// </summary>
        internal static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现有确诊：{0} 的本地化字符串。
        /// </summary>
        internal static string NowConfirmed {
            get {
                return ResourceManager.GetString("NowConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现有重症：{0} 的本地化字符串。
        /// </summary>
        internal static string NowSevere {
            get {
                return ResourceManager.GetString("NowSevere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现有疑似：{0} 的本地化字符串。
        /// </summary>
        internal static string NowSuspected {
            get {
                return ResourceManager.GetString("NowSuspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （数据来源：腾讯新闻） 的本地化字符串。
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5 的本地化字符串。
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
