//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ricky8955555.CoolQ {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ricky8955555.CoolQ.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Minop Bot (项目名：Ricky8955555.CoolQ)
        ///By Ricky8955555
        ///基于 CoolQ (智能机器人软件) &amp; HuajiTech.CoolQ (SDK) 开发的一款插件
        ///
        ///感谢 CoolQ 提供软件支持 和 SYC 提供 SDK 支持
        ///
        ///Ricky8955555.CoolQ 项目 (GitHub): {0}
        ///HuajiTech.CoolQ (SDK) 项目 (GitHub): {1}
        ///酷Q 官网: {2} 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析配置失败（{0}） 的本地化字符串。
        /// </summary>
        internal static string ConfigurationCannotBeLoaded {
            get {
                return ResourceManager.GetString("ConfigurationCannotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置加载 的本地化字符串。
        /// </summary>
        internal static string ConfigurationLoading {
            get {
                return ResourceManager.GetString("ConfigurationLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://cqp.cc 的本地化字符串。
        /// </summary>
        internal static string CoolQURL {
            get {
                return ResourceManager.GetString("CoolQURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5 的本地化字符串。
        /// </summary>
        internal static string CovidStatusApiURL {
            get {
                return ResourceManager.GetString("CovidStatusApiURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 (￣３￣)a ，具体用法：{0} 的本地化字符串。
        /// </summary>
        internal static string FeatureIncorrectUsage {
            get {
                return ResourceManager.GetString("FeatureIncorrectUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1}是怎么回事呢？{0}相信大家都很熟悉，但是{0}{1}是怎么回事呢，下面就让小编带大家一起了解吧。
        ///{0}{1}，其实就是{2}，大家可能会很惊讶{0}怎么会{1}呢？但事实就是这样，小编也感到非常惊讶。
        ///这就是关于{0}{1}的事情了，大家有什么想法呢，欢迎在评论区告诉小编一起讨论哦！ 的本地化字符串。
        /// </summary>
        internal static string MarketingTemplate {
            get {
                return ResourceManager.GetString("MarketingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://music.163.com/api/search/pc?s={0}&amp;type=1 的本地化字符串。
        /// </summary>
        internal static string MusicApiURL {
            get {
                return ResourceManager.GetString("MusicApiURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/ricky8955555/Ricky8955555.CoolQ 的本地化字符串。
        /// </summary>
        internal static string ProjectURL {
            get {
                return ResourceManager.GetString("ProjectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/huajitech/coolq-dotnet-sdk 的本地化字符串。
        /// </summary>
        internal static string SDKProjectURL {
            get {
                return ResourceManager.GetString("SDKProjectURL", resourceCulture);
            }
        }
    }
}
